CREATE DATABASE IF NOT EXISTS `PTM`; USE `PTM`;
DROP TABLE IF EXISTS `user`;
DROP TABLE IF EXISTS `role`;

CREATE TABLE IF NOT EXISTS `PTM`.`role` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`roleCode` VARCHAR(255) NULL DEFAULT NULL,
	`roleName` VARCHAR(255) NULL DEFAULT NULL,
	`description` VARCHAR(255) NULL DEFAULT NULL,
	PRIMARY KEY (`Id`)
)DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `PTM`.`user` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(255) NULL DEFAULT NULL,
	`surName` VARCHAR(255) NULL DEFAULT NULL,
	`roleCode` VARCHAR(255) NULL DEFAULT NULL,
	`username` VARCHAR(255) NULL DEFAULT NULL,
	`password` VARCHAR(255) NULL DEFAULT NULL,
	PRIMARY KEY (`id`)
)DEFAULT CHARSET=utf8;