INSERT INTO `role` (`id`, `name`) VALUES ('1', 'admin');
INSERT INTO `role` (`id`, `name`) VALUES ('2', 'sup');
INSERT INTO `role` (`id`, `name`) VALUES ('3', 'user');

INSERT INTO `user` (`id`, `password`, `username`) VALUES ('1', '$2a$10$ZAtx9YUEBQa0un9/DRuM2.EJ5HzISAdASZP7beScbgqw2LX846QhK', 'admins');
INSERT INTO `user` (`id`, `password`, `username`) VALUES ('2', '$2a$10$ZAtx9YUEBQa0un9/DRuM2.EJ5HzISAdASZP7beScbgqw2LX846QhK', 'Epis1');
INSERT INTO `user` (`id`, `password`, `username`) VALUES ('3', '$2a$10$ZAtx9YUEBQa0un9/DRuM2.EJ5HzISAdASZP7beScbgqw2LX846QhK', 'Epis11');

INSERT INTO `user_role` (`user_id`, `role_id`) VALUES ('1', '1');
INSERT INTO `user_role` (`user_id`, `role_id`) VALUES ('2', '2');
INSERT INTO `user_role` (`user_id`, `role_id`) VALUES ('3', '3');

INSERT INTO `MASTER_DATA` (`valueKey`, `text`, `groupType`) VALUES ('N', 'NON_VAT', 'VAT_RATE');
INSERT INTO `MASTER_DATA` (`valueKey`, `text`, `groupType`) VALUES ('0', '0', 'VAT_RATE');
INSERT INTO `MASTER_DATA` (`valueKey`, `text`, `groupType`) VALUES ('3', '3', 'VAT_RATE');
INSERT INTO `MASTER_DATA` (`valueKey`, `text`, `groupType`) VALUES ('7', '7', 'VAT_RATE');

INSERT INTO `MASTER_DATA` (`valueKey`, `text`, `groupType`) VALUES ('001', '001', 'BANK_CODE');
INSERT INTO `MASTER_DATA` (`valueKey`, `text`, `groupType`) VALUES ('002', '002', 'BANK_CODE');
INSERT INTO `MASTER_DATA` (`valueKey`, `text`, `groupType`) VALUES ('004', '004', 'BANK_CODE');
INSERT INTO `MASTER_DATA` (`valueKey`, `text`, `groupType`) VALUES ('005', '005', 'BANK_CODE');
INSERT INTO `MASTER_DATA` (`valueKey`, `text`, `groupType`) VALUES ('006', '006', 'BANK_CODE');
INSERT INTO `MASTER_DATA` (`valueKey`, `text`, `groupType`) VALUES ('007', '007', 'BANK_CODE');
INSERT INTO `MASTER_DATA` (`valueKey`, `text`, `groupType`) VALUES ('008', '008', 'BANK_CODE');
INSERT INTO `MASTER_DATA` (`valueKey`, `text`, `groupType`) VALUES ('009', '009', 'BANK_CODE');
INSERT INTO `MASTER_DATA` (`valueKey`, `text`, `groupType`) VALUES ('010', '010', 'BANK_CODE');
INSERT INTO `MASTER_DATA` (`valueKey`, `text`, `groupType`) VALUES ('011', '011', 'BANK_CODE');
INSERT INTO `MASTER_DATA` (`valueKey`, `text`, `groupType`) VALUES ('012', '012', 'BANK_CODE');
INSERT INTO `MASTER_DATA` (`valueKey`, `text`, `groupType`) VALUES ('013', '013', 'BANK_CODE');
INSERT INTO `MASTER_DATA` (`valueKey`, `text`, `groupType`) VALUES ('014', '014', 'BANK_CODE');
INSERT INTO `MASTER_DATA` (`valueKey`, `text`, `groupType`) VALUES ('015', '015', 'BANK_CODE');
INSERT INTO `MASTER_DATA` (`valueKey`, `text`, `groupType`) VALUES ('016', '016', 'BANK_CODE');
INSERT INTO `MASTER_DATA` (`valueKey`, `text`, `groupType`) VALUES ('017', '017', 'BANK_CODE');
INSERT INTO `MASTER_DATA` (`valueKey`, `text`, `groupType`) VALUES ('019', '019', 'BANK_CODE');
INSERT INTO `MASTER_DATA` (`valueKey`, `text`, `groupType`) VALUES ('020', '020', 'BANK_CODE');
INSERT INTO `MASTER_DATA` (`valueKey`, `text`, `groupType`) VALUES ('021', '021', 'BANK_CODE');
INSERT INTO `MASTER_DATA` (`valueKey`, `text`, `groupType`) VALUES ('022', '022', 'BANK_CODE');
INSERT INTO `MASTER_DATA` (`valueKey`, `text`, `groupType`) VALUES ('023', '023', 'BANK_CODE');
INSERT INTO `MASTER_DATA` (`valueKey`, `text`, `groupType`) VALUES ('024', '024', 'BANK_CODE');
INSERT INTO `MASTER_DATA` (`valueKey`, `text`, `groupType`) VALUES ('025', '025', 'BANK_CODE');
INSERT INTO `MASTER_DATA` (`valueKey`, `text`, `groupType`) VALUES ('026', '026', 'BANK_CODE');
INSERT INTO `MASTER_DATA` (`valueKey`, `text`, `groupType`) VALUES ('027', '027', 'BANK_CODE');
INSERT INTO `MASTER_DATA` (`valueKey`, `text`, `groupType`) VALUES ('028', '028', 'BANK_CODE');
INSERT INTO `MASTER_DATA` (`valueKey`, `text`, `groupType`) VALUES ('029', '029', 'BANK_CODE');
INSERT INTO `MASTER_DATA` (`valueKey`, `text`, `groupType`) VALUES ('030', '030', 'BANK_CODE');
INSERT INTO `MASTER_DATA` (`valueKey`, `text`, `groupType`) VALUES ('031', '031', 'BANK_CODE');
INSERT INTO `MASTER_DATA` (`valueKey`, `text`, `groupType`) VALUES ('032', '032', 'BANK_CODE');
INSERT INTO `MASTER_DATA` (`valueKey`, `text`, `groupType`) VALUES ('033', '033', 'BANK_CODE');
INSERT INTO `MASTER_DATA` (`valueKey`, `text`, `groupType`) VALUES ('034', '034', 'BANK_CODE');
INSERT INTO `MASTER_DATA` (`valueKey`, `text`, `groupType`) VALUES ('035', '035', 'BANK_CODE');
INSERT INTO `MASTER_DATA` (`valueKey`, `text`, `groupType`) VALUES ('039', '039', 'BANK_CODE');
INSERT INTO `MASTER_DATA` (`valueKey`, `text`, `groupType`) VALUES ('040', '040', 'BANK_CODE');
INSERT INTO `MASTER_DATA` (`valueKey`, `text`, `groupType`) VALUES ('045', '045', 'BANK_CODE');
INSERT INTO `MASTER_DATA` (`valueKey`, `text`, `groupType`) VALUES ('047', '047', 'BANK_CODE');
INSERT INTO `MASTER_DATA` (`valueKey`, `text`, `groupType`) VALUES ('052', '052', 'BANK_CODE');
INSERT INTO `MASTER_DATA` (`valueKey`, `text`, `groupType`) VALUES ('053', '053', 'BANK_CODE');
INSERT INTO `MASTER_DATA` (`valueKey`, `text`, `groupType`) VALUES ('065', '065', 'BANK_CODE');
INSERT INTO `MASTER_DATA` (`valueKey`, `text`, `groupType`) VALUES ('066', '066', 'BANK_CODE');
INSERT INTO `MASTER_DATA` (`valueKey`, `text`, `groupType`) VALUES ('067', '067', 'BANK_CODE');
INSERT INTO `MASTER_DATA` (`valueKey`, `text`, `groupType`) VALUES ('069', '069', 'BANK_CODE');
INSERT INTO `MASTER_DATA` (`valueKey`, `text`, `groupType`) VALUES ('070', '070', 'BANK_CODE');
INSERT INTO `MASTER_DATA` (`valueKey`, `text`, `groupType`) VALUES ('071', '071', 'BANK_CODE');
INSERT INTO `MASTER_DATA` (`valueKey`, `text`, `groupType`) VALUES ('073', '073', 'BANK_CODE');
INSERT INTO `MASTER_DATA` (`valueKey`, `text`, `groupType`) VALUES ('079', '079', 'BANK_CODE');
INSERT INTO `MASTER_DATA` (`valueKey`, `text`, `groupType`) VALUES ('098', '098', 'BANK_CODE');

INSERT INTO `MASTER_DATA` (`valueKey`, `text`, `groupType`) VALUES ('001', 'ธนาคารแห่งประเทศไทย', 'BANK_NAME');
INSERT INTO `MASTER_DATA` (`valueKey`, `text`, `groupType`) VALUES ('002', 'ธ.กรุงเทพ จำกัด (มหาชน)', 'BANK_NAME');
INSERT INTO `MASTER_DATA` (`valueKey`, `text`, `groupType`) VALUES ('004', 'ธ.กสิกรไทย จำกัด(มหาชน)', 'BANK_NAME');
INSERT INTO `MASTER_DATA` (`valueKey`, `text`, `groupType`) VALUES ('005', 'The Royal Bank of Scotland', 'BANK_NAME');
INSERT INTO `MASTER_DATA` (`valueKey`, `text`, `groupType`) VALUES ('006', 'ธ.กรุงไทย จำกัด (มหาชน)', 'BANK_NAME');
INSERT INTO `MASTER_DATA` (`valueKey`, `text`, `groupType`) VALUES ('007', 'ธ.สแตนดาร์ดชาร์เตอร์ด', 'BANK_NAME');
INSERT INTO `MASTER_DATA` (`valueKey`, `text`, `groupType`) VALUES ('008', 'ธ.เจพี มอร์แกน เซส', 'BANK_NAME');
INSERT INTO `MASTER_DATA` (`valueKey`, `text`, `groupType`) VALUES ('009', 'ธ.โอเวอร์ซี-ไซนีสแบงกิ้งคอร์ปอเรชั่น', 'BANK_NAME');
INSERT INTO `MASTER_DATA` (`valueKey`, `text`, `groupType`) VALUES ('010', 'ธนาคารแห่งโตเกียว-มิสซูบิชิ', 'BANK_NAME');
INSERT INTO `MASTER_DATA` (`valueKey`, `text`, `groupType`) VALUES ('011', 'ธ.ทหารไทย จำกัด (มหาชน)', 'BANK_NAME');
INSERT INTO `MASTER_DATA` (`valueKey`, `text`, `groupType`) VALUES ('012', 'ธ.ดีบีเอส ไทยทนุ จำกัด (มหาชน)', 'BANK_NAME');
INSERT INTO `MASTER_DATA` (`valueKey`, `text`, `groupType`) VALUES ('013', 'ธ.มหานคร (จำกัด)', 'BANK_NAME');
INSERT INTO `MASTER_DATA` (`valueKey`, `text`, `groupType`) VALUES ('014', 'ธ.ไทยยพาณิชย์ จำกัด(มหาชน)', 'BANK_NAME');
INSERT INTO `MASTER_DATA` (`valueKey`, `text`, `groupType`) VALUES ('015', 'ธ.นครหลวงไทย จำกัด(มหาชน)', 'BANK_NAME');
INSERT INTO `MASTER_DATA` (`valueKey`, `text`, `groupType`) VALUES ('016', 'ธ.ซิตี้แบงค์,เอ็น.เอ.', 'BANK_NAME');
INSERT INTO `MASTER_DATA` (`valueKey`, `text`, `groupType`) VALUES ('017', 'ธ.ซูมิโตโม - มิตซุย แบงกิ้ง คอร์ปอเรชั่น', 'BANK_NAME');
INSERT INTO `MASTER_DATA` (`valueKey`, `text`, `groupType`) VALUES ('019', 'ธ.อูโอบิ รัตนสิน จำกัด(มหาชน)', 'BANK_NAME');
INSERT INTO `MASTER_DATA` (`valueKey`, `text`, `groupType`) VALUES ('020', 'ธ.สแตนดาร์ดชาร์เตอร์ (ไทย) จำกัด(มหาชน)', 'BANK_NAME');
INSERT INTO `MASTER_DATA` (`valueKey`, `text`, `groupType`) VALUES ('021', 'ธ.นครหลวงไทย จำกัด(2)(มหาชน)', 'BANK_NAME');
INSERT INTO `MASTER_DATA` (`valueKey`, `text`, `groupType`) VALUES ('022', 'ธ.ซีไอเอ็มบี ไทย จำกัด(มหาชน)', 'BANK_NAME');
INSERT INTO `MASTER_DATA` (`valueKey`, `text`, `groupType`) VALUES ('023', 'ธ.อาร์ เอซ บี', 'BANK_NAME');
INSERT INTO `MASTER_DATA` (`valueKey`, `text`, `groupType`) VALUES ('024', 'ธนาคาร ยูโอบี จำกัด(มหาชน)', 'BANK_NAME');
INSERT INTO `MASTER_DATA` (`valueKey`, `text`, `groupType`) VALUES ('025', 'ธ.กรุงศรีอยุธยา จำกัด(มหาชน)', 'BANK_NAME');
INSERT INTO `MASTER_DATA` (`valueKey`, `text`, `groupType`) VALUES ('026', 'ธนาคาร เมกะ สากลพาณิชย์ จำกัด (มหาชน)', 'BANK_NAME');
INSERT INTO `MASTER_DATA` (`valueKey`, `text`, `groupType`) VALUES ('027', 'ธนาครแห่งอเมริกา เนชั่นแนล เอสโซซิเอชั่น', 'BANK_NAME');
INSERT INTO `MASTER_DATA` (`valueKey`, `text`, `groupType`) VALUES ('028', 'ธ.เครดิต อะกริกอล', 'BANK_NAME');
INSERT INTO `MASTER_DATA` (`valueKey`, `text`, `groupType`) VALUES ('029', 'ธ.อินเดียน โอเวอร์ซิส์', 'BANK_NAME');
INSERT INTO `MASTER_DATA` (`valueKey`, `text`, `groupType`) VALUES ('030', 'ธ.ออมสิน', 'BANK_NAME');
INSERT INTO `MASTER_DATA` (`valueKey`, `text`, `groupType`) VALUES ('031', 'ธ.ฮ่องกงและเซี่ยงไฮ้', 'BANK_NAME');
INSERT INTO `MASTER_DATA` (`valueKey`, `text`, `groupType`) VALUES ('032', 'ธ.ดอยซ์แบงก์', 'BANK_NAME');
INSERT INTO `MASTER_DATA` (`valueKey`, `text`, `groupType`) VALUES ('033', 'ธนาคารอาคารสงเคราะห์', 'BANK_NAME');
INSERT INTO `MASTER_DATA` (`valueKey`, `text`, `groupType`) VALUES ('034', 'ธ.เพื่อการเกษตรและสหกรณ์(ธกส)', 'BANK_NAME');
INSERT INTO `MASTER_DATA` (`valueKey`, `text`, `groupType`) VALUES ('035', 'ธนาคารเพื่อการส่งออกและนำเข้าแห่งประเทศไทย', 'BANK_NAME');
INSERT INTO `MASTER_DATA` (`valueKey`, `text`, `groupType`) VALUES ('039', 'ธ.มิซูโฮ คอร์ปอเรต จำกัด', 'BANK_NAME');
INSERT INTO `MASTER_DATA` (`valueKey`, `text`, `groupType`) VALUES ('040', 'ธ.เดรสต์เนอร์ เอจี', 'BANK_NAME');
INSERT INTO `MASTER_DATA` (`valueKey`, `text`, `groupType`) VALUES ('045', 'ธ.บีเอ็นพี พารีบาส กรุงเทพฯ', 'BANK_NAME');
INSERT INTO `MASTER_DATA` (`valueKey`, `text`, `groupType`) VALUES ('047', 'ธนาคารเพื่อการอุตสาหกรรมแห่งประเทศญี่ปุ่น', 'BANK_NAME');
INSERT INTO `MASTER_DATA` (`valueKey`, `text`, `groupType`) VALUES ('052', 'ธนาคารแห่งประเทศจีน', 'BANK_NAME');
INSERT INTO `MASTER_DATA` (`valueKey`, `text`, `groupType`) VALUES ('053', 'ธนาคารแห่งโนวาสโกเทีย', 'BANK_NAME');
INSERT INTO `MASTER_DATA` (`valueKey`, `text`, `groupType`) VALUES ('065', 'ธ.ธนชาต จำกัด(มหาชน)', 'BANK_NAME');
INSERT INTO `MASTER_DATA` (`valueKey`, `text`, `groupType`) VALUES ('066', 'ธนาคารอิสลามแห่งประเทศไทย', 'BANK_NAME');
INSERT INTO `MASTER_DATA` (`valueKey`, `text`, `groupType`) VALUES ('067', 'ธนาคารทิสโก้ จำกัด', 'BANK_NAME');
INSERT INTO `MASTER_DATA` (`valueKey`, `text`, `groupType`) VALUES ('069', 'ธ.เกียรตินาคิน', 'BANK_NAME');
INSERT INTO `MASTER_DATA` (`valueKey`, `text`, `groupType`) VALUES ('070', 'ธนาคารไอซีบีซี(ไทย)', 'BANK_NAME');
INSERT INTO `MASTER_DATA` (`valueKey`, `text`, `groupType`) VALUES ('071', 'ธนาคารไทยเครดิต', 'BANK_NAME');
INSERT INTO `MASTER_DATA` (`valueKey`, `text`, `groupType`) VALUES ('073', 'ธนาคารแลนด์ แอนด์ เฮ้าส์ จำกัด(มหาชน)', 'BANK_NAME');
INSERT INTO `MASTER_DATA` (`valueKey`, `text`, `groupType`) VALUES ('079', 'ธนาคารเอเอ็นแซด (ไทย) จำกัด(มหาชน)', 'BANK_NAME');
INSERT INTO `MASTER_DATA` (`valueKey`, `text`, `groupType`) VALUES ('098', 'ธ.ขนาดกลางและขนาดย่อมแห่งประเทศไทย', 'BANK_NAME');

INSERT INTO `MASTER_DATA` (`valueKey`, `text`, `groupType`) VALUES ('BANK_NAME', 'BANK_NAME', 'INITVALUE');
INSERT INTO `MASTER_DATA` (`valueKey`, `text`, `groupType`) VALUES ('VAT_RATE', 'VAT_RATE', 'INITVALUE');





