CREATE DATABASE IF NOT EXISTS `INQUIRY`; USE `INQUIRY`;
DROP TABLE IF EXISTS `ROLE`;
DROP TABLE IF EXISTS `USER`;
DROP TABLE IF EXISTS `USER_ROLE`;
DROP TABLE IF EXISTS `MASTER_DATA`;
DROP TABLE IF EXISTS `QUESTION`;

CREATE TABLE IF NOT EXISTS `INQUIRY`.`ROLE` (
	ID BIGINT(20) NOT NULL AUTO_INCREMENT,
	Name VARCHAR(255) NULL DEFAULT NULL,
	CREATE_BY VARCHAR(20),
	CREATE_DATE TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
	UPDATE_BY VARCHAR(20),
	UPDATE_DATE TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
	PRIMARY KEY (`id`)
)DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `INQUIRY`.`USER` (
	ID BIGINT(20) NOT NULL AUTO_INCREMENT,
	Name VARCHAR(100) NULL DEFAULT NULL,
	SurName VARCHAR(100) NULL DEFAULT NULL,
	Password VARCHAR(255) NULL DEFAULT NULL,
	Username VARCHAR(255) NULL DEFAULT NULL,
	CREATE_BY VARCHAR(20),
	CREATE_DATE TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
	UPDATE_BY VARCHAR(20),
	UPDATE_DATE TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
	LoginFlag VARCHAR(1),
	PRIMARY KEY (`id`),
	UNIQUE KEY `Username` (`Username`)
)DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `INQUIRY`.`USER_ROLE` (
	User_ID BIGINT(20) NOT NULL,
	Role_ID BIGINT(20) NOT NULL,
	PRIMARY KEY (`user_id`, `role_id`)
)DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `INQUIRY`.`MASTER_DATA` (
	ID BIGINT(20) NOT NULL AUTO_INCREMENT,
	KEYCODE VARCHAR(255) NULL DEFAULT NULL,
	VALUE VARCHAR(255) NULL DEFAULT NULL,
	GROUP_KEY VARCHAR(255) NULL DEFAULT NULL,
	TYPE VARCHAR(255) NULL DEFAULT NULL,
	SCORE VARCHAR(255) NULL DEFAULT NULL,
	TEXT_CODE VARCHAR(4000) NULL DEFAULT NULL,
	STATUS VARCHAR(255) NULL DEFAULT NULL,
	CREATE_BY VARCHAR(20),
	CREATE_DATE TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
	UPDATE_BY VARCHAR(20),
	UPDATE_DATE TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
	PRIMARY KEY (`ID`)
)DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `INQUIRY`.`SCORE` (
	ID BIGINT(20) NOT NULL AUTO_INCREMENT,
	GROUP_CODE VARCHAR(255) NULL DEFAULT NULL,
	QUESTION_GROUP VARCHAR(255) NULL DEFAULT NULL,
	QUESTION_CODE VARCHAR(255) NULL DEFAULT NULL,
	SCORE_1 VARCHAR(100) NULL DEFAULT NULL,
	SCORE_2 VARCHAR(100) NULL DEFAULT NULL,
	SCORE_3 VARCHAR(100) NULL DEFAULT NULL,
	SCORE_4 VARCHAR(100) NULL DEFAULT NULL,
	SCORE_5 VARCHAR(100) NULL DEFAULT NULL,
	PRIMARY KEY (`ID`)
)DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `INQUIRY`.`QUESTION` (
	ID BIGINT(20) NOT NULL AUTO_INCREMENT,
	GROUP_CODE VARCHAR(5) NULL DEFAULT NULL,
	SEQ_NO VARCHAR(100) NULL DEFAULT NULL,
	SCORE VARCHAR(1) NULL DEFAULT NULL,
	TYPE VARCHAR(5) NULL DEFAULT NULL,
	QUESTION_CODE VARCHAR(255) NULL DEFAULT NULL,
	CREATE_BY VARCHAR(20),
	CREATE_DATE TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
	UPDATE_BY VARCHAR(20),
	UPDATE_DATE TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
	PRIMARY KEY (`id`)
)DEFAULT CHARSET=utf8;